### ISSUE TITLE
Add 'unsafe-inline' when adding hashes

### ISSUE THREAD

**Issue by papandreou** [papandreou/seespee#2]
For interop with CSP1 compliant browsers:

```
$ seespee https://lodash.com/
Content-Security-Policy: default-src 'none'; img-src 'self' data:; style-src 'self'; script-src 'self' 'sha256-85RLtUiAixnqFeQvOtsiq5HBnq4nAgtgmrVVlIrEwyk=' 'sha256-9gJ3aNComH+MFu3rw5sARPpvBPOF0VxLUsw1xjxmVzE=' 'sha256-euGdatRFmkEGGSWO0jbpFAuN5709ZGDaFjCqNnYocQM='
```

In this case `'unsafe-inline'` should be added to the `script-src` directive.

**Comment by papandreou** [comment]
Fixed in 81f89d8, released in 1.7.0.

**Comment by jdalton** [comment]
🤘

**Comment by jdalton** [comment]
In a csp validator I'm getting a warning like:
```
 The 'unsafe-inline' keyword-source has no effect in source lists that contain hash-source or nonce-source.
```

**Comment by papandreou** [comment]
Then that validator doesn't take CSP level 1 compliant browsers into account (Edge 13+14, Safari 8+9+9.1). They would block your inline script(s) if you didn't list `'unsafe-inline'`.

**Comment by jdalton** [comment]
Ah nice! Thanks for the clarification.
