### ISSUE TITLE
expose API for programmatic use.

### ISSUE THREAD

**Issue by jdalton** [papandreou/seespee#3]
I'd like to generate the csp header as part of my site build step. It'd be rad to be able to tap into it (maybe through a promise).

**Comment by Munter** [comment]
Assetgraph is the programmatic api. The transform queue exposes a then-able, which is not a full promise though. The [ContentSecurityPolicy transform](https://github.com/assetgraph/assetgraph/blob/master/lib/assets/ContentSecurityPolicy.js) can be set to update existing policies in each page separately. If you want it in your netlify `_headers` file you'll need to pull it out from there, which is what seespee does here: https://github.com/papandreou/seespee/blob/master/lib/seespee.js#L55-L69

If you feel adventurous you should give assetgraph-builder a whirl. It works extremely well with jekyll output. I set up my own blog on netlify, also with CSP in `_headers` and it works really well https://github.com/Munter/mntr.dk/blob/master/package.json#L10

**Comment by jdalton** [comment]
Cool! For now I using `require('child_process').exec` to invoke `seespee` at the moment.

**Comment by papandreou** [comment]
`seespee` does add some convenience that's not available with the `reviewContentSecurityPolicy` transform (and wouldn't make sense to build into it), such as creating a CSP from scratch and handling initial HTTP redirects. I think a programmatic API is warranted.

**Comment by papandreou** [comment]
Fixed in 1.9.0.

**Comment by jdalton** [comment]
You rock! Thank you!
